// Generated by view binder compiler. Do not edit!
package ws.xsoh.etar.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.LinearLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import ws.xsoh.etar.R;

public final class DateIntervalFragmentBinding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final Button calculateButton;

  @NonNull
  public final TextView endDateLabel;

  @NonNull
  public final TextView endDateText;

  @NonNull
  public final TextView resultText;

  @NonNull
  public final TextView startDateLabel;

  @NonNull
  public final TextView startDateText;

  private DateIntervalFragmentBinding(@NonNull LinearLayout rootView,
      @NonNull Button calculateButton, @NonNull TextView endDateLabel,
      @NonNull TextView endDateText, @NonNull TextView resultText, @NonNull TextView startDateLabel,
      @NonNull TextView startDateText) {
    this.rootView = rootView;
    this.calculateButton = calculateButton;
    this.endDateLabel = endDateLabel;
    this.endDateText = endDateText;
    this.resultText = resultText;
    this.startDateLabel = startDateLabel;
    this.startDateText = startDateText;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static DateIntervalFragmentBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static DateIntervalFragmentBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.date_interval_fragment, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static DateIntervalFragmentBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.calculate_button;
      Button calculateButton = ViewBindings.findChildViewById(rootView, id);
      if (calculateButton == null) {
        break missingId;
      }

      id = R.id.end_date_label;
      TextView endDateLabel = ViewBindings.findChildViewById(rootView, id);
      if (endDateLabel == null) {
        break missingId;
      }

      id = R.id.end_date_text;
      TextView endDateText = ViewBindings.findChildViewById(rootView, id);
      if (endDateText == null) {
        break missingId;
      }

      id = R.id.result_text;
      TextView resultText = ViewBindings.findChildViewById(rootView, id);
      if (resultText == null) {
        break missingId;
      }

      id = R.id.start_date_label;
      TextView startDateLabel = ViewBindings.findChildViewById(rootView, id);
      if (startDateLabel == null) {
        break missingId;
      }

      id = R.id.start_date_text;
      TextView startDateText = ViewBindings.findChildViewById(rootView, id);
      if (startDateText == null) {
        break missingId;
      }

      return new DateIntervalFragmentBinding((LinearLayout) rootView, calculateButton, endDateLabel,
          endDateText, resultText, startDateLabel, startDateText);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
