// Generated by view binder compiler. Do not edit!
package ws.xsoh.etar.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.EditText;
import android.widget.LinearLayout;
import android.widget.RadioButton;
import android.widget.RadioGroup;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import ws.xsoh.etar.R;

public final class DateCalculationFragmentBinding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final RadioButton backwardButton;

  @NonNull
  public final Button calculateButton;

  @NonNull
  public final EditText daysInput;

  @NonNull
  public final RadioGroup directionGroup;

  @NonNull
  public final RadioButton forwardButton;

  @NonNull
  public final TextView resultText;

  @NonNull
  public final TextView startDateLabel;

  @NonNull
  public final TextView startDateText;

  private DateCalculationFragmentBinding(@NonNull LinearLayout rootView,
      @NonNull RadioButton backwardButton, @NonNull Button calculateButton,
      @NonNull EditText daysInput, @NonNull RadioGroup directionGroup,
      @NonNull RadioButton forwardButton, @NonNull TextView resultText,
      @NonNull TextView startDateLabel, @NonNull TextView startDateText) {
    this.rootView = rootView;
    this.backwardButton = backwardButton;
    this.calculateButton = calculateButton;
    this.daysInput = daysInput;
    this.directionGroup = directionGroup;
    this.forwardButton = forwardButton;
    this.resultText = resultText;
    this.startDateLabel = startDateLabel;
    this.startDateText = startDateText;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static DateCalculationFragmentBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static DateCalculationFragmentBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.date_calculation_fragment, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static DateCalculationFragmentBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.backward_button;
      RadioButton backwardButton = ViewBindings.findChildViewById(rootView, id);
      if (backwardButton == null) {
        break missingId;
      }

      id = R.id.calculate_button;
      Button calculateButton = ViewBindings.findChildViewById(rootView, id);
      if (calculateButton == null) {
        break missingId;
      }

      id = R.id.days_input;
      EditText daysInput = ViewBindings.findChildViewById(rootView, id);
      if (daysInput == null) {
        break missingId;
      }

      id = R.id.direction_group;
      RadioGroup directionGroup = ViewBindings.findChildViewById(rootView, id);
      if (directionGroup == null) {
        break missingId;
      }

      id = R.id.forward_button;
      RadioButton forwardButton = ViewBindings.findChildViewById(rootView, id);
      if (forwardButton == null) {
        break missingId;
      }

      id = R.id.result_text;
      TextView resultText = ViewBindings.findChildViewById(rootView, id);
      if (resultText == null) {
        break missingId;
      }

      id = R.id.start_date_label;
      TextView startDateLabel = ViewBindings.findChildViewById(rootView, id);
      if (startDateLabel == null) {
        break missingId;
      }

      id = R.id.start_date_text;
      TextView startDateText = ViewBindings.findChildViewById(rootView, id);
      if (startDateText == null) {
        break missingId;
      }

      return new DateCalculationFragmentBinding((LinearLayout) rootView, backwardButton,
          calculateButton, daysInput, directionGroup, forwardButton, resultText, startDateLabel,
          startDateText);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
