// Generated by view binder compiler. Do not edit!
package ws.xsoh.etar.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.ImageButton;
import android.widget.RelativeLayout;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.google.android.material.button.MaterialButton;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import ws.xsoh.etar.R;

public final class EditEventCustomActionbarBinding implements ViewBinding {
  @NonNull
  private final RelativeLayout rootView;

  @NonNull
  public final ImageButton actionCancel;

  @NonNull
  public final MaterialButton actionDone;

  private EditEventCustomActionbarBinding(@NonNull RelativeLayout rootView,
      @NonNull ImageButton actionCancel, @NonNull MaterialButton actionDone) {
    this.rootView = rootView;
    this.actionCancel = actionCancel;
    this.actionDone = actionDone;
  }

  @Override
  @NonNull
  public RelativeLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static EditEventCustomActionbarBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static EditEventCustomActionbarBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.edit_event_custom_actionbar, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static EditEventCustomActionbarBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.action_cancel;
      ImageButton actionCancel = ViewBindings.findChildViewById(rootView, id);
      if (actionCancel == null) {
        break missingId;
      }

      id = R.id.action_done;
      MaterialButton actionDone = ViewBindings.findChildViewById(rootView, id);
      if (actionDone == null) {
        break missingId;
      }

      return new EditEventCustomActionbarBinding((RelativeLayout) rootView, actionCancel,
          actionDone);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
