// Generated by view binder compiler. Do not edit!
package ws.xsoh.etar.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.CheckBox;
import android.widget.EditText;
import android.widget.ScrollView;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import ws.xsoh.etar.R;

public final class LunarConverterFragmentBinding implements ViewBinding {
  @NonNull
  private final ScrollView rootView;

  @NonNull
  public final Button convertToGregorianButton;

  @NonNull
  public final TextView gregorianDateLabel;

  @NonNull
  public final TextView gregorianDateText;

  @NonNull
  public final TextView gregorianResultText;

  @NonNull
  public final TextView gregorianToLunarTitle;

  @NonNull
  public final CheckBox leapMonthCheckbox;

  @NonNull
  public final TextView lunarDateLabel;

  @NonNull
  public final TextView lunarDateText;

  @NonNull
  public final EditText lunarDayInput;

  @NonNull
  public final EditText lunarMonthInput;

  @NonNull
  public final TextView lunarToGregorianTitle;

  @NonNull
  public final EditText lunarYearInput;

  private LunarConverterFragmentBinding(@NonNull ScrollView rootView,
      @NonNull Button convertToGregorianButton, @NonNull TextView gregorianDateLabel,
      @NonNull TextView gregorianDateText, @NonNull TextView gregorianResultText,
      @NonNull TextView gregorianToLunarTitle, @NonNull CheckBox leapMonthCheckbox,
      @NonNull TextView lunarDateLabel, @NonNull TextView lunarDateText,
      @NonNull EditText lunarDayInput, @NonNull EditText lunarMonthInput,
      @NonNull TextView lunarToGregorianTitle, @NonNull EditText lunarYearInput) {
    this.rootView = rootView;
    this.convertToGregorianButton = convertToGregorianButton;
    this.gregorianDateLabel = gregorianDateLabel;
    this.gregorianDateText = gregorianDateText;
    this.gregorianResultText = gregorianResultText;
    this.gregorianToLunarTitle = gregorianToLunarTitle;
    this.leapMonthCheckbox = leapMonthCheckbox;
    this.lunarDateLabel = lunarDateLabel;
    this.lunarDateText = lunarDateText;
    this.lunarDayInput = lunarDayInput;
    this.lunarMonthInput = lunarMonthInput;
    this.lunarToGregorianTitle = lunarToGregorianTitle;
    this.lunarYearInput = lunarYearInput;
  }

  @Override
  @NonNull
  public ScrollView getRoot() {
    return rootView;
  }

  @NonNull
  public static LunarConverterFragmentBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static LunarConverterFragmentBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.lunar_converter_fragment, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static LunarConverterFragmentBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.convert_to_gregorian_button;
      Button convertToGregorianButton = ViewBindings.findChildViewById(rootView, id);
      if (convertToGregorianButton == null) {
        break missingId;
      }

      id = R.id.gregorian_date_label;
      TextView gregorianDateLabel = ViewBindings.findChildViewById(rootView, id);
      if (gregorianDateLabel == null) {
        break missingId;
      }

      id = R.id.gregorian_date_text;
      TextView gregorianDateText = ViewBindings.findChildViewById(rootView, id);
      if (gregorianDateText == null) {
        break missingId;
      }

      id = R.id.gregorian_result_text;
      TextView gregorianResultText = ViewBindings.findChildViewById(rootView, id);
      if (gregorianResultText == null) {
        break missingId;
      }

      id = R.id.gregorian_to_lunar_title;
      TextView gregorianToLunarTitle = ViewBindings.findChildViewById(rootView, id);
      if (gregorianToLunarTitle == null) {
        break missingId;
      }

      id = R.id.leap_month_checkbox;
      CheckBox leapMonthCheckbox = ViewBindings.findChildViewById(rootView, id);
      if (leapMonthCheckbox == null) {
        break missingId;
      }

      id = R.id.lunar_date_label;
      TextView lunarDateLabel = ViewBindings.findChildViewById(rootView, id);
      if (lunarDateLabel == null) {
        break missingId;
      }

      id = R.id.lunar_date_text;
      TextView lunarDateText = ViewBindings.findChildViewById(rootView, id);
      if (lunarDateText == null) {
        break missingId;
      }

      id = R.id.lunar_day_input;
      EditText lunarDayInput = ViewBindings.findChildViewById(rootView, id);
      if (lunarDayInput == null) {
        break missingId;
      }

      id = R.id.lunar_month_input;
      EditText lunarMonthInput = ViewBindings.findChildViewById(rootView, id);
      if (lunarMonthInput == null) {
        break missingId;
      }

      id = R.id.lunar_to_gregorian_title;
      TextView lunarToGregorianTitle = ViewBindings.findChildViewById(rootView, id);
      if (lunarToGregorianTitle == null) {
        break missingId;
      }

      id = R.id.lunar_year_input;
      EditText lunarYearInput = ViewBindings.findChildViewById(rootView, id);
      if (lunarYearInput == null) {
        break missingId;
      }

      return new LunarConverterFragmentBinding((ScrollView) rootView, convertToGregorianButton,
          gregorianDateLabel, gregorianDateText, gregorianResultText, gregorianToLunarTitle,
          leapMonthCheckbox, lunarDateLabel, lunarDateText, lunarDayInput, lunarMonthInput,
          lunarToGregorianTitle, lunarYearInput);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
